travisapp/config/routes.rb
Rails.application.routes.draw do
  
  get 'admin/:id' => 'admin#show'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :recipes

  root 'pages#show'

end

travisapp/app/models/admin.rb
class Admin < ActiveRecord::Base

	has_many :recipes, dependent: :destroy
	validates :username, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX}
	validates :password, presence: true, length: { minimum: 6 }
	has_secure_password
	
end

travisapp/app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :admin
  validates :admin_id, presence: true
  # Should change the content length.
  validates :description, presence: true, length: { maximum: 800 }
  validates :title, presence: true, length: { maximum: 140 }
  default_scope -> { order(created_at: :desc) }
  delegate :username, :email, to: :admin, prefix: true
end

travisapp/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def show
  	@admin = Admin.last
  end
end

travisapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

travisapp/app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def show
		@recipe = Recipe.first
		render "home"
	end
end

travisapp/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def index
  	@recipes = Recipe.all
  end

  def show
  end

  def new
    if logged_in?
      @recipe = current_admin.recipes.build
      @admin = current_admin
      
    else
      flash[:danger] = "Sorry you have to be logged in to create a new recipe."
      redirect_to root_path
    end
  end

  def create
    @admin = current_admin
    @recipe = @admin.recipes.new(recipe_params)
    if @recipe.save
      flash[:success] = "Recipe Created!"
      redirect_to root_path
    else
      render "new"
    end
  end

  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end

  def edit
  end

  def update
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end


  def recipe_params
    params.require(:recipe).permit(:title, :content)
  end  
end

travisapp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	admin = Admin.find_by(email: params[:session][:email].downcase)
  	if admin && admin.authenticate(params[:session][:password])
      puts "logged in"
      log_in admin
  		redirect_to root_path
  	else
  		flash.now[:danger] = 'Inavlid email or password combination.'
      render "new"
  	end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

travisapp/app/helpers/admin_helper.rb
module AdminHelper
end

travisapp/app/helpers/application_helper.rb
module ApplicationHelper
end

travisapp/app/helpers/recipes_helper.rb
module RecipesHelper
end

travisapp/app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(admin)
		session[:admin_id] = admin.id
	end

	def current_admin
		@current_admin ||= Admin.find_by(id: session[:admin_id])
	end

	def logged_in?
		!current_admin.nil?
	end

	def log_out
		session.delete(:admin_id)
		@current_admin = nil
	end
end

travisapp/app/views/_partials/_navigation.html.haml
%header
  %nav.nav.has-shadow
    .container
      .nav-left
        .nav-item.is-brand= link_to "Travis", root_path
      .nav-right.nav-menu
        .nav-item= link_to "Recipes", recipes_path
        .nav-item= link_to "New Recipe", new_recipe_path
        -if logged_in?
          .nav-item= current_admin.username

travisapp/app/views/admin/show.html.haml
%h1
  Hello #{@admin.username}

travisapp/app/views/layouts/application.html.haml
!!!
%html
%head
%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
%title Travisapp
%meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"
= javascript_include_tag 'application', 'data-turbolinks-track' => true
= csrf_meta_tags
%body
= render '_partials/navigation'
- flash.each do |message_type, message|
  %div{:class => "alert alert-#{message_type}"}= message
= yield
%hr
%footer.footer
  .container.is-fluid
    .content.has-text-centered
      - if logged_in?
        = @current_admin.username
        = link_to "Log out", logout_path, method: :delete
      - else
        = link_to "Log in", login_path
      = debug(params) if Rails.env.development?

travisapp/app/views/pages/home.html.haml
%section.hero.is-large
	.hero-body.hero-img
		.container.hero-text
			%h1#welcome-text.title Hi.
			%h3#welcome-message.subtitle My name is Travis Starwalt.
#intro-section.center-text.container
	%p#intro-section-text
		Lick butt and make a weird face. Spot something, big eyes, big eyes, crouch, shake butt, prepare to pounce. Cat slap dog in face claw drapes, for scratch leg; meow for can opener to feed me yet hopped up on catnip, but hide when guests come over scratch at the door then walk away. Roll on the floor purring your whiskers off meow for food, then when human fills food dish, take a few bites of food and continue meowing sit in window and stare ooo, a bird! yum scratch the furniture but if it fits, i sits but claw drapes, but meowwww. Cat slap dog in face play time, for see owner, run in terror so destroy couch as revenge. Missing until dinner time bathe private parts with tongue then lick owner's face meow. Kitty loves pigs find something else more interesting eat
.container
	.columns
		.column.is-three-quarters
			.box
				.media
					%figure.media-left
						.image.is-64x64
							= image_tag "knife_plate.png"
					.media-content
						%h1.title.is-1 Latest Recipe
						.recipe-container
							.recipe-title
								%h2.title.is-3= @recipe.title
							.recipe-content
								%p= @recipe.description.to_s
								%p= @recipe.ingredient_list
							.recipe-footer.level
								.level-left
									%p.level-item Created by: #{ @recipe.admin.username }
								.level-right
									= link_to "Check it out", recipe_path(@recipe), class: "level-item"
		.column
			=image_tag "http://placekitten.com/400/300", class: "img-responsive"

travisapp/app/views/recipes/index.html.haml
- @recipes.each do |rec|
  %ul
    %li= rec.title
    %li= rec.description
    %li= rec.ingredient_list
    - if rec.admin_id != nil
      %li= rec.admin_username
    = link_to "View More", recipe_path(rec.id)
    -if logged_in?
      = link_to "(Delete)",  recipe_path(rec.id), method: :delete
  %hr

travisapp/app/views/recipes/new.html.haml
%h1 Hi there. this is recipes
= form_for(@recipe, class: "new_recipe_form") do |f|
  = f.text_field :title, placeholder: "Title", class: "input-area"
  %br
  = f.text_area :description, placeholder: "This is where you put the recipe", class: "input-area"
  %br
  = f.text_area :ingredient_list, placeholder: "Ingredients...", class: "input-area"
  %br
  = f.submit "Add Recipe", class: "submit-button"

travisapp/app/views/recipes/show.html.haml
%h1 Recipes#show
%p Find me in app/views/recipes/show.html.erb
%p= @recipe.description